name: cart
description: A new Flutter package project.
version: 0.0.1
publish_to: none
homepage: core

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  categories: 
      path: ../categories
  core: 
      path: ../core
  go_router: ^11.1.4
  flutter_svg: ^2.0.7
  flutter_animate: ^4.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

uses-material-design: true"