name: delivery_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0

  flutter_animate: ^4.2.0+1
  go_router: ^12.1.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

material_design: true

flutter:
  uses-material-design: true
  
  assets:
    - assets/imgs/
    - assets/svgs/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.ttf
          weight: 400