name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  go_router: ^11.0.0
  splash:
    path: ../splash
  categories:
    path: ../categories
  home:
    path: ../home
  cart:
    path: ../cart
  profile:
    path: ../profile
  payment:
    path: ../payment


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Bold.ttf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display/SF-Pro-Display-Regular.ttf
          weight: 400